# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/LTBP',
                'doc_host': 'https://JeremyDemlow.github.io',
                'git_url': 'https://github.com/JeremyDemlow/LTBP',
                'lib_path': 'LTBP'},
  'syms': {'LTBP.core': {'LTBP.core.foo': ('core.html#foo', 'LTBP/core.py')}}}